name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
        # make depends on poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Run linter
        run: |
          poetry run make lint
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageCommand: make test-coverage
          debug: true
          verifyDownload: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
