name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          pytest testfiel
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
